version: '3'
services:
  solr:
    container_name: solr-conv
    image: solr:9.0.0
    restart: unless-stopped
    ports:
     - 8983:8983
    environment:
      - SOLR_JAVA_MEM=-Xms2g -Xmx2g
    volumes:
     - ./solr-data:/var/solr/data
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - documents